//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFS.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SuccessApiMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuccessApiMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PFS.Application.Resources.SuccessApiMessages", typeof(SuccessApiMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product added to cart.
        /// </summary>
        public static string AddedToCart {
            get {
                return ResourceManager.GetString("AddedToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product added to wishlist.
        /// </summary>
        public static string AddWishList {
            get {
                return ResourceManager.GetString("AddWishList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Blocked Successfully.
        /// </summary>
        public static string BlockCategory {
            get {
                return ResourceManager.GetString("BlockCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Feched Succefully.
        /// </summary>
        public static string CartFeched {
            get {
                return ResourceManager.GetString("CartFeched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Category Added Successfully.
        /// </summary>
        public static string CategoryAdd {
            get {
                return ResourceManager.GetString("CategoryAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Product Created Successfully.
        /// </summary>
        public static string CreateProduct {
            get {
                return ResourceManager.GetString("CreateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Deleted Successfully.
        /// </summary>
        public static string DeleteCategory {
            get {
                return ResourceManager.GetString("DeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Category Fetched .
        /// </summary>
        public static string FetchAllCategory {
            get {
                return ResourceManager.GetString("FetchAllCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category  Fetched .
        /// </summary>
        public static string FetchCategoryById {
            get {
                return ResourceManager.GetString("FetchCategoryById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Fetched.
        /// </summary>
        public static string FetchProduct {
            get {
                return ResourceManager.GetString("FetchProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Product is Fetched By Category.
        /// </summary>
        public static string FetchProductByCategory {
            get {
                return ResourceManager.GetString("FetchProductByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetched Users Order.
        /// </summary>
        public static string FetchUserOrders {
            get {
                return ResourceManager.GetString("FetchUserOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetched item in Wishlist.
        /// </summary>
        public static string FetchWishlist {
            get {
                return ResourceManager.GetString("FetchWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Logged Successfully.
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Fetched.
        /// </summary>
        public static string OrderDetails {
            get {
                return ResourceManager.GetString("OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Placed Successfully.
        /// </summary>
        public static string PlaceOrder {
            get {
                return ResourceManager.GetString("PlaceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart item removed successfully.
        /// </summary>
        public static string RemoveCartItem {
            get {
                return ResourceManager.GetString("RemoveCartItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Removed From Wishlist.
        /// </summary>
        public static string RemoveWishlist {
            get {
                return ResourceManager.GetString("RemoveWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Result.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Completed Registration.
        /// </summary>
        public static string SuccessRegistation {
            get {
                return ResourceManager.GetString("SuccessRegistation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token refreshed successfully.
        /// </summary>
        public static string TokenRefresh {
            get {
                return ResourceManager.GetString("TokenRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Updated Successfully .
        /// </summary>
        public static string UpdateCategory {
            get {
                return ResourceManager.GetString("UpdateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Updated Successfully.
        /// </summary>
        public static string UpdatedCart {
            get {
                return ResourceManager.GetString("UpdatedCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Updated Successfully.
        /// </summary>
        public static string UpdateProduct {
            get {
                return ResourceManager.GetString("UpdateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User blocked successfully.
        /// </summary>
        public static string UserBlocked {
            get {
                return ResourceManager.GetString("UserBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User fetched successfully.
        /// </summary>
        public static string UserFetched {
            get {
                return ResourceManager.GetString("UserFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users fetched successfully.
        /// </summary>
        public static string UsersFetched {
            get {
                return ResourceManager.GetString("UsersFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User unblocked successfully.
        /// </summary>
        public static string UserUnbloked {
            get {
                return ResourceManager.GetString("UserUnbloked", resourceCulture);
            }
        }
    }
}
